dist: trusty
sudo: true
language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

install:
  - pip install pip pipenv -U
  - pipenv install --dev --skip-lock
script:
  - make qa
  - make coverage
after_success:
  - pipenv run codecov
branches:
  only:
    - master
